# Nebra Docs Configuration
# Inspired by ocelot's docs, but with a space-like theme and Nebra's structure.
site_name: "nebra"
site_url: https://nebra.astrosky.eco
site_author: Emily Hunt
site_description: >-
  A simple Python tool that can stream or send time-critical scientific data live and for free on the ATProtocol.

repo_url: https://github.com/emilyhunt/nebra
repo_name: nebra

theme:
  name: material
  locale: en
  custom_dir: docs/_overrides
  features:
    - navigation.sections  # Sections are included in the navigation on the left.
    - header.autohide  # Header disappears as you scroll.
    - search.suggest  # Suggested search.
    - search.highlight
    - search.share
    - navigation.tabs  # Shows tabs instead of endless header list.
  palette:
    # Dark mode / space-like theme
    - scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github  # GitHub logo in top right
    logo: material/satellite-variant  # Space-like logo
  favicon: _static/favicon.png

markdown_extensions:
  - pymdownx.arithmatex:  # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences  # Syntax highlighting with the Material theme.
  - pymdownx.details  # Allow hidden expandable regions denoted by ???
  - pymdownx.snippets:  # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "¤"  # Adds a clickable permalink to each section heading
      toc_depth: 4
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search  # Default search plugin
  - autorefs  # Cross-links to headings
  - social  # Makes a preview image for each page
  - mkdocs-jupyter  # Allows for display of notebooks directly in docs site
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy  # Render docs as numpy style
            show_source: false
            show_root_heading: true
            show_object_full_path: false
            members_order: source
            inherited_members: true  # Allow looking up inherited methods

nav:
  - Introduction:
    - Overview: 'index.md'
    - Installation: 'installation.md'
    - ATProtocol: 'atproto.md'
    - Changelog: 'changelog.md'
    - Report an issue: 'issue.md'
  - Examples:
    - Sending Data: 'examples/sending.ipynb'
    - Streaming Data: 'examples/streaming.ipynb'
    - Rebroadcasting Data: 'examples/rebroadcasting.ipynb'
  - API Reference:
    - Core: 'api/core.md'
    - Utilities: 'api/utilities.md'